name: xarray-array-testing-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - hypothesis
  - xarray
  - numpy
  - pip
  - pip:
      - --pre -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --extra-index-url https://pypi.org/simple
      - xarray
